[screens]

[screens.edids]
acerB193 = """
    00ffffffffffff003873752200000000
    011c0103a01e1764eae4de9e544a9723
    1c4c5400080081808140810001019500
    01010101010164190040410026301888
    360000c010000018023a801871382d40
    582c4500dd0c1100001e662150b05100
    1b304070360032313400001e000000fa
    00819981c081fc01010101950f0a0104
    02031b61439084022309070783010000
    67030c0020008028e2000f8c0ad08a20
    e02d10103e9600a05a00000000000000
    00000000000000000000000000000000
    00000000000000000000000000000000
    00000000000000000000000000000000
    00000000000000000000000000000000
    0000000000000000000000000000002e
    """
samsungSyncMaster = """
    00ffffffffffff0004ef010031304e43
    2d170103a01e1761eae4de9e544a9723
    1c4c5400080081808140810001019500
    01010101010164190040410026301888
    360000c010000018023a801871382d40
    582c4500dd0c1100001e662150b05100
    1b304070360032313400001e000000fa
    00819981c081fc01010101950f0a013c
    02031b61230907078301000067030c00
    2000802d43908402e2000f8c0ad08a20
    e02d10103e9600a05a00000000000000
    00000000000000000000000000000000
    00000000000000000000000000000000
    00000000000000000000000000000000
    00000000000000000000000000000000
    00000000000000000000000000000029
    """

[screens.setup-commands]
acerB193 = "xrandr --output HDMI-2 --mode 1280x960 --right-of eDP-1"
samsungSyncMaster = "xrandr --output HDMI-2 --mode 1920x1080 --right-of eDP-1"

